name: CI
on:
  push:
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - env:
        IMAGE_NAME: "docker.pkg.github.com/orihoch/postgres-docker-readonly/postgres-docker-readonly"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u orihoch --password-stdin &&\
        if docker pull "${IMAGE_NAME}:latest"; then
          CACHE_FROM_ARG="--cache-from ${IMAGE_NAME}:latest"
        else
          CACHE_FROM_ARG=""
        fi &&\
        docker build $CACHE_FROM_ARG -t postgres-readonly . &&\
        docker tag postgres-readonly "${IMAGE_NAME}:${GITHUB_SHA}" &&\
        docker push "${IMAGE_NAME}:${GITHUB_SHA}" &&\
        if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
          docker tag postgres-readonly "${IMAGE_NAME}:latest" &&\
          docker push "${IMAGE_NAME}:latest"
        fi
